### ISSUE TITLE
Could this plugin support Microsoft Edge?

### ISSUE THREAD

**Issue by SoraKasvgano** [notlmn/copy-as-markdown#25]
I mean if it is possible to upload it on Microsoft edge store.......
thanks

**Comment by notlmn** [comment]
You can install the version [released](https://chrome.google.com/webstore/detail/copy-as-markdown/nlaionblcaejecbkcillglodmmfhjhfi/) to Chrome Web Store on Edge.

We're not going to publish a specific version on the Edge addon store (there was one, I unpublished it because there was a lot of maintenance involved and no automated releases).
